/*
 * Patient Health Record Service
 * Create your PHR ID to track your health records in one place.
 *
 * OpenAPI spec version: V.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

<<<<<<< HEAD
<<<<<<< HEAD:UserManagement/src/main/java/in/gov/abdm/eua/userManagement/dto/phr/login/AuthInitResponse.java
=======
>>>>>>> 9dbb9f3cbb1548b28a5c1ef4dea8ca3f1144235a
package in.gov.abdm.eua.userManagement.dto.phr.login;

import com.fasterxml.jackson.annotation.JsonInclude;
import in.gov.abdm.eua.userManagement.dto.phr.ServiceResponse;
<<<<<<< HEAD
=======
package in.gov.abdm.eua.service.dto.phr.login;

import com.fasterxml.jackson.annotation.JsonInclude;
import in.gov.abdm.eua.service.dto.phr.ServiceResponse;
>>>>>>> 9dbb9f3cbb1548b28a5c1ef4dea8ca3f1144235a:EUAclient/src/main/java/in/gov/abdm/eua/service/dto/phr/login/AuthInitResponse.java
=======
>>>>>>> 9dbb9f3cbb1548b28a5c1ef4dea8ca3f1144235a
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AuthInitResponse
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class AuthInitResponse extends ServiceResponse {
    private String transactionId;

    private String requesterId;

    private String authMode;


}
